services:
  - type: web
    name: precio-dolar-live
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: PUBLIC_BASE_URL
        value: https://precio-dolar-live.onrender.com